### ISSUE TITLE
Variables names are not readable

### ISSUE THREAD

**Issue by ferdaber** [adamrossnelson/crossreg#1]
When reading the `.py` file, I cannot grok the files easily because y-minus-y-bar is not:

(a) following PEP standards
(b) not easily readable

Python does not have variable length limits, the variable names should be refactored to snake case to better follow PEP and be more readable, I suggest:
`ymybar => y_minus_y_bar`

**Comment by adamrossnelson** [comment]
Thanks for the comments.
